version: "3.9"

services:
  laravel-app:
    build: .
    container_name: laravel-app
    ports:
      - "8081:80"   # ✅ Apache listens on port 80 inside container
    depends_on:
      mysql-db:
        condition: service_healthy
    environment:
      DB_HOST: mysql-db
      DB_PORT: 3306
      DB_DATABASE: energix
      DB_USERNAME: root
      DB_PASSWORD: rootpassword
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  mysql-db:
    image: mysql:8.0  # Stable
    container_name: mysql-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword  # Matches Laravel
      MYSQL_DATABASE: energix
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -hlocalhost -uroot -prootpassword || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 30s

volumes:
  db_data:
