version: "3.9"

services:
  laravel-app:
    build: .
    container_name: laravel-app
    ports:
      - "8081:8080"   # Map container's 8080 to host 8081
    depends_on:
      - mysql-db
    env_file:
      - .env

  mysql-db:
    image: mysql:8.1
    container_name: mysql-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: energix
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db_data:
