services:
  app:
    image: my-laravel-app:latest
    container_name: laravel-app
    restart: unless-stopped
    ports:
      - "8081:9000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/var/www/html

  db:
    image: mysql:8.1
    container_name: mysql-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword  # only root password
      MYSQL_DATABASE: energix
      # remove MYSQL_USER and MYSQL_PASSWORD
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
