version: "3.9"

services:
  laravel-app:
    build: .
    container_name: laravel-app
    ports:
      - "8081:8080"
    depends_on:
      mysql-db:
        condition: service_healthy  # **WAIT FOR MYSQL HEALTHY**
    environment:
      DB_HOST: mysql-db
      DB_PORT: 3306
      DB_DATABASE: energix
      DB_USERNAME: root
      DB_PASSWORD: ""  # **MATCH MYSQL_ROOT_PASSWORD**
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 3

  mysql-db:
    image: mysql:8.1
    container_name: mysql-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ""  # **EMPTY PASSWORD**
      MYSQL_DATABASE: energix
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:  # **MYSQL HEALTH CHECK**
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p''"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  db_data:
