version: "3.9"

services:
  laravel-app:
    build: .
    container_name: laravel-app
    ports:
      - "8081:8080"
    depends_on:
      - mysql-db
    environment:
      DB_HOST: mysql-db
      DB_PORT: 3306
      DB_DATABASE: energix
      DB_USERNAME: root
      DB_PASSWORD: ""

  mysql-db:
    image: mysql:8.1
    container_name: mysql-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: energix
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db_data:
