version: "3.9"

services:
  laravel-app:
    build: .
    container_name: laravel-app
    depends_on:
      - mysql-db
    environment:
      DB_HOST: mysql-db
      DB_PORT: 3306
      DB_DATABASE: energix
      DB_USERNAME: root
      DB_PASSWORD: rootpassword
    volumes:
      - .:/var/www/html
    env_file:
      - .env
    expose:
      - "9000"
    networks:
      - app-network

  nginx:
    image: nginx:stable
    container_name: nginx
    ports:
      - "8081:80"
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - laravel-app
    networks:
      - app-network

  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: energix
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
